# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_alloc <- function() {
    .Call('_RcppStdVector_test_alloc', PACKAGE = 'RcppStdVector')
}

test_modify <- function(x) {
    .Call('_RcppStdVector_test_modify', PACKAGE = 'RcppStdVector', x)
}

test_list <- function(x) {
    .Call('_RcppStdVector_test_list', PACKAGE = 'RcppStdVector', x)
}

test_char <- function() {
    .Call('_RcppStdVector_test_char', PACKAGE = 'RcppStdVector')
}

test_copy_chr <- function(x) {
    .Call('_RcppStdVector_test_copy_chr', PACKAGE = 'RcppStdVector', x)
}

test_copy_rcpp_chr <- function(x) {
    .Call('_RcppStdVector_test_copy_rcpp_chr', PACKAGE = 'RcppStdVector', x)
}

